version: '3.7'

networks:
    core:

volumes:
    db01:

services:

    web:
        container_name: web
        build: .
        ports:
            - "0.0.0.0:8000:8000"
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: db
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=case_deloitte
        volumes:
            - db01:/var/lib/postgresql/data
        networks:
            - core
        ports:
            - "0.0.0.0:5432:5432"

