# Generated by Django 4.2 on 2023-04-19 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='grades',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discipline', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='grades',
            name='report_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcard', verbose_name='Boletim'),
        ),
    ]
